//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equin.ApplicationFramework.Properties
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landlord2.BindingListView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add an external item to the view. Use AddNew() or add to source list instead. 的本地化字符串。
        /// </summary>
        internal static string CannotAddItem {
            get {
                return ResourceManager.GetString("CannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a new item due to no object being provided in the AddingNew event and a lack of default public constructor. 的本地化字符串。
        /// </summary>
        internal static string CannotAddNewItem {
            get {
                return ResourceManager.GetString("CannotAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a new item when NewItemsList is null. 的本地化字符串。
        /// </summary>
        internal static string CannotAddWhenNewItemsListNull {
            get {
                return ResourceManager.GetString("CannotAddWhenNewItemsListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot clear this view. 的本地化字符串。
        /// </summary>
        internal static string CannotClearView {
            get {
                return ResourceManager.GetString("CannotClearView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot insert an external item into this collection. 的本地化字符串。
        /// </summary>
        internal static string CannotInsertItem {
            get {
                return ResourceManager.GetString("CannotInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set an item in the view. 的本地化字符串。
        /// </summary>
        internal static string CannotSetItem {
            get {
                return ResourceManager.GetString("CannotSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 includeDelegate cannot be null. 的本地化字符串。
        /// </summary>
        internal static string IncludeDelegateCannotBeNull {
            get {
                return ResourceManager.GetString("IncludeDelegateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item in list is not of type {0}. 的本地化字符串。
        /// </summary>
        internal static string InvalidListItemType {
            get {
                return ResourceManager.GetString("InvalidListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source list does not implement IList. 的本地化字符串。
        /// </summary>
        internal static string InvalidSourceList {
            get {
                return ResourceManager.GetString("InvalidSourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item was not of type {0}. 的本地化字符串。
        /// </summary>
        internal static string ItemTypeIncorrect {
            get {
                return ResourceManager.GetString("ItemTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (no filter) 的本地化字符串。
        /// </summary>
        internal static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (predicate filter) 的本地化字符串。
        /// </summary>
        internal static string PredicateFilter {
            get {
                return ResourceManager.GetString("PredicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} does not exist in type {1}. 的本地化字符串。
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source list already added to the view. 的本地化字符串。
        /// </summary>
        internal static string SourceListAlreadyAdded {
            get {
                return ResourceManager.GetString("SourceListAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source list is not in the view. 的本地化字符串。
        /// </summary>
        internal static string SourceListNotFound {
            get {
                return ResourceManager.GetString("SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SourceLists cannot be null. 的本地化字符串。
        /// </summary>
        internal static string SourceListsNull {
            get {
                return ResourceManager.GetString("SourceListsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronized access to the view is not supported. 的本地化字符串。
        /// </summary>
        internal static string SyncAccessNotSupported {
            get {
                return ResourceManager.GetString("SyncAccessNotSupported", resourceCulture);
            }
        }
    }
}
