//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET99_DogTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ET99_DogTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 d15336fef55d9053bedd65c2cb8f5a6e 的本地化字符串。
        /// </summary>
        internal static string HMAC_MD5 {
            get {
                return ResourceManager.GetString("HMAC_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2141221B 的本地化字符串。
        /// </summary>
        internal static string PID {
            get {
                return ResourceManager.GetString("PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFFFFFFF 的本地化字符串。
        /// </summary>
        internal static string PID_Default {
            get {
                return ResourceManager.GetString("PID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 416080100100084469001 的本地化字符串。
        /// </summary>
        internal static string PID种子 {
            get {
                return ResourceManager.GetString("PID种子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABD5414789594810 的本地化字符串。
        /// </summary>
        internal static string SOPIN {
            get {
                return ResourceManager.GetString("SOPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFFFFFFFFFFFFFFF 的本地化字符串。
        /// </summary>
        internal static string SOPIN_Default {
            get {
                return ResourceManager.GetString("SOPIN_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 420101663462759001 的本地化字符串。
        /// </summary>
        internal static string SOPIN种子 {
            get {
                return ResourceManager.GetString("SOPIN种子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15 的本地化字符串。
        /// </summary>
        internal static string SOPIN重试次数 {
            get {
                return ResourceManager.GetString("SOPIN重试次数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8cfac3342adfee5e 的本地化字符串。
        /// </summary>
        internal static string UserPIN {
            get {
                return ResourceManager.GetString("UserPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFFFFFFFFFFFFFFF 的本地化字符串。
        /// </summary>
        internal static string UserPIN_Default {
            get {
                return ResourceManager.GetString("UserPIN_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string UserPIN重试次数 {
            get {
                return ResourceManager.GetString("UserPIN重试次数", resourceCulture);
            }
        }
    }
}
