//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landlord2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap attach_16_dis {
            get {
                object obj = ResourceManager.GetObject("attach_16_dis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idea_16 {
            get {
                object obj = ResourceManager.GetObject("idea_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idea_16_dis {
            get {
                object obj = ResourceManager.GetObject("idea_16_dis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idea_16_hot {
            get {
                object obj = ResourceManager.GetObject("idea_16_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房24Add {
            get {
                object obj = ResourceManager.GetObject("客房24Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房24Del {
            get {
                object obj = ResourceManager.GetObject("客房24Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房24Edit {
            get {
                object obj = ResourceManager.GetObject("客房24Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房48Add {
            get {
                object obj = ResourceManager.GetObject("客房48Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房48Del {
            get {
                object obj = ResourceManager.GetObject("客房48Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房48Edit {
            get {
                object obj = ResourceManager.GetObject("客房48Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房出租24 {
            get {
                object obj = ResourceManager.GetObject("客房出租24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房出租48 {
            get {
                object obj = ResourceManager.GetObject("客房出租48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房续租24 {
            get {
                object obj = ResourceManager.GetObject("客房续租24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房续租48 {
            get {
                object obj = ResourceManager.GetObject("客房续租48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房退租24 {
            get {
                object obj = ResourceManager.GetObject("客房退租24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 客房退租48 {
            get {
                object obj = ResourceManager.GetObject("客房退租48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.whwater.gov.cn/3637.html 的本地化字符串。
        /// </summary>
        internal static string 武汉市城市供水价格表 {
            get {
                return ResourceManager.GetString("武汉市城市供水价格表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.53 的本地化字符串。
        /// </summary>
        internal static string 武汉市天然气价默认值 {
            get {
                return ResourceManager.GetString("武汉市天然气价默认值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.90,0,25;2.45,25,33;3.00,33 的本地化字符串。
        /// </summary>
        internal static string 武汉市阶梯水价默认值 {
            get {
                return ResourceManager.GetString("武汉市阶梯水价默认值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.573 的本地化字符串。
        /// </summary>
        internal static string 武汉市阶梯电价默认值 {
            get {
                return ResourceManager.GetString("武汉市阶梯电价默认值", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap 源房24Add {
            get {
                object obj = ResourceManager.GetObject("源房24Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 源房24Del {
            get {
                object obj = ResourceManager.GetObject("源房24Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 源房24Edit {
            get {
                object obj = ResourceManager.GetObject("源房24Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 源房48Add {
            get {
                object obj = ResourceManager.GetObject("源房48Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 源房48Del {
            get {
                object obj = ResourceManager.GetObject("源房48Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 源房48Edit {
            get {
                object obj = ResourceManager.GetObject("源房48Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缴费24 {
            get {
                object obj = ResourceManager.GetObject("缴费24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缴费48 {
            get {
                object obj = ResourceManager.GetObject("缴费48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缴费明细24 {
            get {
                object obj = ResourceManager.GetObject("缴费明细24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缴费明细48 {
            get {
                object obj = ResourceManager.GetObject("缴费明细48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
