





//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsE26EA78CD79C75ED15E86513BEAC48F0BD5BC7B9C6C38F2CA26F1F1726213193))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// 此类型包含在设计时生成的 EntitySets 和 AssociationSets 的视图。
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsE26EA78CD79C75ED15E86513BEAC48F0BD5BC7B9C6C38F2CA26F1F1726213193 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// 构造函数存储各区的视图，以及根据元数据和映射结束和视图生成的哈希值。
        /// </Summary>
        public ViewsForBaseEntitySetsE26EA78CD79C75ED15E86513BEAC48F0BD5BC7B9C6C38F2CA26F1F1726213193()
        {
            this.EdmEntityContainerName = "Landlord2Entities";
            this.StoreEntityContainerName = "Landlord2ModelStoreContainer";
            this.HashOverMappingClosure = "84a70fdd9577b3081d6d89cf8bf1a9a7d57a106a6f8efb2d0870b1f6e15cdfee";
            this.HashOverAllExtentViews = "aba4429ab1c5220727633e40b23e3d7e6deac3bce46aa24e09bd604f8048d488";
            this.ViewCount = 22;
        }
        
        /// <Summary>
        /// 此方法返回给定索引的视图。
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.DailyLosses 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.DailyLosses", @"
    SELECT VALUE -- Constructing DailyLosses
        [Landlord2Model.Store.DailyLosses](T1.[DailyLosses_源房ID], T1.[DailyLosses_客房ID], T1.[DailyLosses_项目], T1.[DailyLosses_支出金额], T1.[DailyLosses_支出日期], T1.[DailyLosses_备注], T1.DailyLosses_ID)
    FROM (
        SELECT 
            T.[源房ID] AS [DailyLosses_源房ID], 
            T.[客房ID] AS [DailyLosses_客房ID], 
            T.[项目] AS [DailyLosses_项目], 
            T.[支出金额] AS [DailyLosses_支出金额], 
            T.[支出日期] AS [DailyLosses_支出日期], 
            T.[备注] AS [DailyLosses_备注], 
            T.ID AS DailyLosses_ID, 
            True AS _from0
        FROM Landlord2Entities.DailyLosses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.DailyLosses 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.DailyLosses", @"
    SELECT VALUE -- Constructing DailyLosses
        [Landlord2Model.DailyLosses](T1.[DailyLosses_源房ID], T1.[DailyLosses_客房ID], T1.[DailyLosses_项目], T1.[DailyLosses_支出金额], T1.[DailyLosses_支出日期], T1.[DailyLosses_备注], T1.DailyLosses_ID)
    FROM (
        SELECT 
            T.[源房ID] AS [DailyLosses_源房ID], 
            T.[客房ID] AS [DailyLosses_客房ID], 
            T.[项目] AS [DailyLosses_项目], 
            T.[支出金额] AS [DailyLosses_支出金额], 
            T.[支出日期] AS [DailyLosses_支出日期], 
            T.[备注] AS [DailyLosses_备注], 
            T.ID AS DailyLosses_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.DailyLosses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.DecorationDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.DecorationDetail", @"
    SELECT VALUE -- Constructing DecorationDetail
        [Landlord2Model.Store.DecorationDetail](T1.[DecorationDetail_日期], T1.[DecorationDetail_项目名称], T1.[DecorationDetail_规格], T1.[DecorationDetail_数量], T1.[DecorationDetail_单位], T1.[DecorationDetail_单价], T1.[DecorationDetail_购买地点], T1.[DecorationDetail_备注], T1.[DecorationDetail_源房ID], T1.[DecorationDetail_装修分类], T1.DecorationDetail_ID)
    FROM (
        SELECT 
            T.[日期] AS [DecorationDetail_日期], 
            T.[项目名称] AS [DecorationDetail_项目名称], 
            T.[规格] AS [DecorationDetail_规格], 
            T.[数量] AS [DecorationDetail_数量], 
            T.[单位] AS [DecorationDetail_单位], 
            T.[单价] AS [DecorationDetail_单价], 
            T.[购买地点] AS [DecorationDetail_购买地点], 
            T.[备注] AS [DecorationDetail_备注], 
            T.[源房ID] AS [DecorationDetail_源房ID], 
            T.[装修分类] AS [DecorationDetail_装修分类], 
            T.ID AS DecorationDetail_ID, 
            True AS _from0
        FROM Landlord2Entities.DecorationDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.GuestRoom 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.GuestRoom", "\r\n    SELECT VALUE -- Constructing GuestRoom\r\n        [Landlord2Model.Store.Guest" +
                    "Room](T1.[GuestRoom_命名], T1.[GuestRoom_面积], T1.[GuestRoom_含厨房], T1.[GuestRoom_含卫" +
                    "生间], T1.[GuestRoom_租户], T1.[GuestRoom_联系地址], T1.[GuestRoom_身份证号], T1.[GuestRoom_" +
                    "电话1], T1.[GuestRoom_电话2], T1.[GuestRoom_期始], T1.[GuestRoom_期止], T1.[GuestRoom_月租" +
                    "金], T1.[GuestRoom_押金], T1.[GuestRoom_支付月数], T1.[GuestRoom_租赁协议照片1], T1.[GuestRoo" +
                    "m_租赁协议照片2], T1.[GuestRoom_租赁协议照片3], T1.[GuestRoom_备注], T1.[GuestRoom_水始码], T1.[G" +
                    "uestRoom_电始码], T1.[GuestRoom_气始码], T1.[GuestRoom_月物业费], T1.[GuestRoom_月宽带费], T1." +
                    "[GuestRoom_月厨房费], T1.[GuestRoom_中介费用], T1.GuestRoom_ID, T1.[GuestRoom_源房ID])\r\n  " +
                    "  FROM (\r\n        SELECT \r\n            T.[命名] AS [GuestRoom_命名], \r\n            T" +
                    ".[面积] AS [GuestRoom_面积], \r\n            T.[含厨房] AS [GuestRoom_含厨房], \r\n           " +
                    " T.[含卫生间] AS [GuestRoom_含卫生间], \r\n            T.[租户] AS [GuestRoom_租户], \r\n       " +
                    "     T.[联系地址] AS [GuestRoom_联系地址], \r\n            T.[身份证号] AS [GuestRoom_身份证号], \r" +
                    "\n            T.[电话1] AS [GuestRoom_电话1], \r\n            T.[电话2] AS [GuestRoom_电话2" +
                    "], \r\n            T.[期始] AS [GuestRoom_期始], \r\n            T.[期止] AS [GuestRoom_期止" +
                    "], \r\n            T.[月租金] AS [GuestRoom_月租金], \r\n            T.[押金] AS [GuestRoom_" +
                    "押金], \r\n            T.[支付月数] AS [GuestRoom_支付月数], \r\n            T.[租赁协议照片1] AS [G" +
                    "uestRoom_租赁协议照片1], \r\n            T.[租赁协议照片2] AS [GuestRoom_租赁协议照片2], \r\n         " +
                    "   T.[租赁协议照片3] AS [GuestRoom_租赁协议照片3], \r\n            T.[备注] AS [GuestRoom_备注], \r" +
                    "\n            T.[水始码] AS [GuestRoom_水始码], \r\n            T.[电始码] AS [GuestRoom_电始码" +
                    "], \r\n            T.[气始码] AS [GuestRoom_气始码], \r\n            T.[月物业费] AS [GuestRoo" +
                    "m_月物业费], \r\n            T.[月宽带费] AS [GuestRoom_月宽带费], \r\n            T.[月厨房费] AS [" +
                    "GuestRoom_月厨房费], \r\n            T.[中介费用] AS [GuestRoom_中介费用], \r\n            T.ID " +
                    "AS GuestRoom_ID, \r\n            T.[源房ID] AS [GuestRoom_源房ID], \r\n            True " +
                    "AS _from0\r\n        FROM Landlord2Entities.GuestRoom AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.GuestRoomRentalDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.GuestRoomRentalDetail", @"
    SELECT VALUE -- Constructing GuestRoomRentalDetail
        [Landlord2Model.Store.GuestRoomRentalDetail](T1.[GuestRoomRentalDetail_起付日期], T1.[GuestRoomRentalDetail_止付日期], T1.[GuestRoomRentalDetail_付款日期], T1.[GuestRoomRentalDetail_水止码], T1.[GuestRoomRentalDetail_电止码], T1.[GuestRoomRentalDetail_气止码], T1.[GuestRoomRentalDetail_应付金额], T1.[GuestRoomRentalDetail_实付金额], T1.[GuestRoomRentalDetail_付款人], T1.[GuestRoomRentalDetail_收款人], T1.[GuestRoomRentalDetail_备注], T1.[GuestRoomRentalDetail_客房ID], T1.GuestRoomRentalDetail_ID)
    FROM (
        SELECT 
            T.[起付日期] AS [GuestRoomRentalDetail_起付日期], 
            T.[止付日期] AS [GuestRoomRentalDetail_止付日期], 
            T.[付款日期] AS [GuestRoomRentalDetail_付款日期], 
            T.[水止码] AS [GuestRoomRentalDetail_水止码], 
            T.[电止码] AS [GuestRoomRentalDetail_电止码], 
            T.[气止码] AS [GuestRoomRentalDetail_气止码], 
            T.[应付金额] AS [GuestRoomRentalDetail_应付金额], 
            T.[实付金额] AS [GuestRoomRentalDetail_实付金额], 
            T.[付款人] AS [GuestRoomRentalDetail_付款人], 
            T.[收款人] AS [GuestRoomRentalDetail_收款人], 
            T.[备注] AS [GuestRoomRentalDetail_备注], 
            T.[客房ID] AS [GuestRoomRentalDetail_客房ID], 
            T.ID AS GuestRoomRentalDetail_ID, 
            True AS _from0
        FROM Landlord2Entities.GuestRoomRentalDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.GuestRoomRentHistory 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2372);
            viewString.Append("\r\n    SELECT VALUE -- Constructing GuestRoomRentHistory\r\n        [Landlord2Model");
            viewString.Append(".Store.GuestRoomRentHistory](T1.[GuestRoomRentHistory_租户], T1.[GuestRoomRentHist");
            viewString.Append("ory_联系地址], T1.[GuestRoomRentHistory_身份证号], T1.[GuestRoomRentHistory_电话1], T1.[Gu");
            viewString.Append("estRoomRentHistory_电话2], T1.[GuestRoomRentHistory_期始], T1.[GuestRoomRentHistory_");
            viewString.Append("期止], T1.[GuestRoomRentHistory_月租金], T1.[GuestRoomRentHistory_押金], T1.[GuestRoomR");
            viewString.Append("entHistory_支付月数], T1.[GuestRoomRentHistory_备注], T1.[GuestRoomRentHistory_客房ID], ");
            viewString.Append("T1.GuestRoomRentHistory_ID, T1.[GuestRoomRentHistory_租赁协议照片1], T1.[GuestRoomRent");
            viewString.Append("History_租赁协议照片2], T1.[GuestRoomRentHistory_租赁协议照片3], T1.[GuestRoomRentHistory_水始");
            viewString.Append("码], T1.[GuestRoomRentHistory_电始码], T1.[GuestRoomRentHistory_气始码], T1.[GuestRoomR");
            viewString.Append("entHistory_月物业费], T1.[GuestRoomRentHistory_月宽带费], T1.[GuestRoomRentHistory_月厨房费]");
            viewString.Append(", T1.[GuestRoomRentHistory_中介费用], T1.[GuestRoomRentHistory_状态], T1.[GuestRoomRen");
            viewString.Append("tHistory_操作日期])\r\n    FROM (\r\n        SELECT \r\n            T.[租户] AS [GuestRoomRe");
            viewString.Append("ntHistory_租户], \r\n            T.[联系地址] AS [GuestRoomRentHistory_联系地址], \r\n        ");
            viewString.Append("    T.[身份证号] AS [GuestRoomRentHistory_身份证号], \r\n            T.[电话1] AS [GuestRoom");
            viewString.Append("RentHistory_电话1], \r\n            T.[电话2] AS [GuestRoomRentHistory_电话2], \r\n       ");
            viewString.Append("     T.[期始] AS [GuestRoomRentHistory_期始], \r\n            T.[期止] AS [GuestRoomRent");
            viewString.Append("History_期止], \r\n            T.[月租金] AS [GuestRoomRentHistory_月租金], \r\n            ");
            viewString.Append("T.[押金] AS [GuestRoomRentHistory_押金], \r\n            T.[支付月数] AS [GuestRoomRentHis");
            viewString.Append("tory_支付月数], \r\n            T.[备注] AS [GuestRoomRentHistory_备注], \r\n            T.[");
            viewString.Append("客房ID] AS [GuestRoomRentHistory_客房ID], \r\n            T.ID AS GuestRoomRentHistory");
            viewString.Append("_ID, \r\n            T.[租赁协议照片1] AS [GuestRoomRentHistory_租赁协议照片1], \r\n            ");
            viewString.Append("T.[租赁协议照片2] AS [GuestRoomRentHistory_租赁协议照片2], \r\n            T.[租赁协议照片3] AS [Gue");
            viewString.Append("stRoomRentHistory_租赁协议照片3], \r\n            T.[水始码] AS [GuestRoomRentHistory_水始码],");
            viewString.Append(" \r\n            T.[电始码] AS [GuestRoomRentHistory_电始码], \r\n            T.[气始码] AS [");
            viewString.Append("GuestRoomRentHistory_气始码], \r\n            T.[月物业费] AS [GuestRoomRentHistory_月物业费]");
            viewString.Append(", \r\n            T.[月宽带费] AS [GuestRoomRentHistory_月宽带费], \r\n            T.[月厨房费] ");
            viewString.Append("AS [GuestRoomRentHistory_月厨房费], \r\n            T.[中介费用] AS [GuestRoomRentHistory_");
            viewString.Append("中介费用], \r\n            T.[状态] AS [GuestRoomRentHistory_状态], \r\n            T.[操作日期]");
            viewString.Append(" AS [GuestRoomRentHistory_操作日期], \r\n            True AS _from0\r\n        FROM Land");
            viewString.Append("lord2Entities.GuestRoomRentHistory AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.GuestRoomRentHistory", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.SourceRoom 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2558);
            viewString.Append("\r\n    SELECT VALUE -- Constructing SourceRoom\r\n        [Landlord2Model.Store.Sou");
            viewString.Append("rceRoom](T1.[SourceRoom_房名], T1.[SourceRoom_用途], T1.[SourceRoom_结构], T1.[SourceR");
            viewString.Append("oom_建筑面积], T1.[SourceRoom_室], T1.[SourceRoom_厅], T1.[SourceRoom_卫], T1.[SourceRo");
            viewString.Append("om_装修], T1.[SourceRoom_权证号], T1.[SourceRoom_房东], T1.[SourceRoom_联系地址], T1.[Sourc");
            viewString.Append("eRoom_身份证号], T1.[SourceRoom_电话1], T1.[SourceRoom_电话2], T1.[SourceRoom_押金], T1.[S");
            viewString.Append("ourceRoom_支付月数], T1.[SourceRoom_租赁协议照片1], T1.[SourceRoom_租赁协议照片2], T1.[SourceRoo");
            viewString.Append("m_租赁协议照片3], T1.[SourceRoom_备注], T1.[SourceRoom_月物业费], T1.[SourceRoom_水始码], T1.[S");
            viewString.Append("ourceRoom_电始码], T1.[SourceRoom_气始码], T1.[SourceRoom_中介费用], T1.[SourceRoom_月卫生费],");
            viewString.Append(" T1.[SourceRoom_源房东银行卡], T1.[SourceRoom_水表编号], T1.[SourceRoom_电表编号], T1.[SourceR");
            viewString.Append("oom_气表编号], T1.[SourceRoom_水务代扣卫生费], T1.[SourceRoom_月宽带费], T1.[SourceRoom_阶梯水价], ");
            viewString.Append("T1.[SourceRoom_阶梯电价], T1.[SourceRoom_气单价], T1.SourceRoom_ID)\r\n    FROM (\r\n      ");
            viewString.Append("  SELECT \r\n            T.[房名] AS [SourceRoom_房名], \r\n            T.[用途] AS [Sourc");
            viewString.Append("eRoom_用途], \r\n            T.[结构] AS [SourceRoom_结构], \r\n            T.[建筑面积] AS [S");
            viewString.Append("ourceRoom_建筑面积], \r\n            T.[室] AS [SourceRoom_室], \r\n            T.[厅] AS [");
            viewString.Append("SourceRoom_厅], \r\n            T.[卫] AS [SourceRoom_卫], \r\n            T.[装修] AS [S");
            viewString.Append("ourceRoom_装修], \r\n            T.[权证号] AS [SourceRoom_权证号], \r\n            T.[房东] A");
            viewString.Append("S [SourceRoom_房东], \r\n            T.[联系地址] AS [SourceRoom_联系地址], \r\n            T.");
            viewString.Append("[身份证号] AS [SourceRoom_身份证号], \r\n            T.[电话1] AS [SourceRoom_电话1], \r\n      ");
            viewString.Append("      T.[电话2] AS [SourceRoom_电话2], \r\n            T.[押金] AS [SourceRoom_押金], \r\n  ");
            viewString.Append("          T.[支付月数] AS [SourceRoom_支付月数], \r\n            T.[租赁协议照片1] AS [SourceRoo");
            viewString.Append("m_租赁协议照片1], \r\n            T.[租赁协议照片2] AS [SourceRoom_租赁协议照片2], \r\n            T.[");
            viewString.Append("租赁协议照片3] AS [SourceRoom_租赁协议照片3], \r\n            T.[备注] AS [SourceRoom_备注], \r\n   ");
            viewString.Append("         T.[月物业费] AS [SourceRoom_月物业费], \r\n            T.[水始码] AS [SourceRoom_水始码");
            viewString.Append("], \r\n            T.[电始码] AS [SourceRoom_电始码], \r\n            T.[气始码] AS [SourceRo");
            viewString.Append("om_气始码], \r\n            T.[中介费用] AS [SourceRoom_中介费用], \r\n            T.[月卫生费] AS ");
            viewString.Append("[SourceRoom_月卫生费], \r\n            T.[源房东银行卡] AS [SourceRoom_源房东银行卡], \r\n          ");
            viewString.Append("  T.[水表编号] AS [SourceRoom_水表编号], \r\n            T.[电表编号] AS [SourceRoom_电表编号], \r\n");
            viewString.Append("            T.[气表编号] AS [SourceRoom_气表编号], \r\n            T.[水务代扣卫生费] AS [SourceR");
            viewString.Append("oom_水务代扣卫生费], \r\n            T.[月宽带费] AS [SourceRoom_月宽带费], \r\n            T.[阶梯水价");
            viewString.Append("] AS [SourceRoom_阶梯水价], \r\n            T.[阶梯电价] AS [SourceRoom_阶梯电价], \r\n         ");
            viewString.Append("   T.[气单价] AS [SourceRoom_气单价], \r\n            T.ID AS SourceRoom_ID, \r\n         ");
            viewString.Append("   True AS _from0\r\n        FROM Landlord2Entities.SourceRoom AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.SourceRoom", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.SourceRoomCheck 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.SourceRoomCheck", @"
    SELECT VALUE -- Constructing SourceRoomCheck
        [Landlord2Model.Store.SourceRoomCheck](T1.[SourceRoomCheck_抄表日期(水)], T1.[SourceRoomCheck_水止码], T1.[SourceRoomCheck_水账户余额], T1.[SourceRoomCheck_抄表日期(电)], T1.[SourceRoomCheck_电止码], T1.[SourceRoomCheck_电账户余额], T1.[SourceRoomCheck_抄表日期(气)], T1.[SourceRoomCheck_气表剩余字数], T1.[SourceRoomCheck_核查人], T1.[SourceRoomCheck_核查时间], T1.[SourceRoomCheck_备注], T1.[SourceRoomCheck_源房ID], T1.SourceRoomCheck_ID)
    FROM (
        SELECT 
            T.[抄表日期_水_] AS [SourceRoomCheck_抄表日期(水)], 
            T.[水止码] AS [SourceRoomCheck_水止码], 
            T.[水账户余额] AS [SourceRoomCheck_水账户余额], 
            T.[抄表日期_电_] AS [SourceRoomCheck_抄表日期(电)], 
            T.[电止码] AS [SourceRoomCheck_电止码], 
            T.[电账户余额] AS [SourceRoomCheck_电账户余额], 
            T.[抄表日期_气_] AS [SourceRoomCheck_抄表日期(气)], 
            T.[气表剩余字数] AS [SourceRoomCheck_气表剩余字数], 
            T.[核查人] AS [SourceRoomCheck_核查人], 
            T.[核查时间] AS [SourceRoomCheck_核查时间], 
            T.[备注] AS [SourceRoomCheck_备注], 
            T.[源房ID] AS [SourceRoomCheck_源房ID], 
            T.ID AS SourceRoomCheck_ID, 
            True AS _from0
        FROM Landlord2Entities.SourceRoomCheck AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.SourceRoomPaymentDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.SourceRoomPaymentDetail", @"
    SELECT VALUE -- Constructing SourceRoomPaymentDetail
        [Landlord2Model.Store.SourceRoomPaymentDetail](T1.[SourceRoomPaymentDetail_缴费时间], T1.[SourceRoomPaymentDetail_缴费金额], T1.[SourceRoomPaymentDetail_期始], T1.[SourceRoomPaymentDetail_期止], T1.[SourceRoomPaymentDetail_付款人], T1.[SourceRoomPaymentDetail_收款人], T1.[SourceRoomPaymentDetail_备注], T1.[SourceRoomPaymentDetail_源房ID], T1.[SourceRoomPaymentDetail_缴费项], T1.SourceRoomPaymentDetail_ID)
    FROM (
        SELECT 
            T.[缴费时间] AS [SourceRoomPaymentDetail_缴费时间], 
            T.[缴费金额] AS [SourceRoomPaymentDetail_缴费金额], 
            T.[期始] AS [SourceRoomPaymentDetail_期始], 
            T.[期止] AS [SourceRoomPaymentDetail_期止], 
            T.[付款人] AS [SourceRoomPaymentDetail_付款人], 
            T.[收款人] AS [SourceRoomPaymentDetail_收款人], 
            T.[备注] AS [SourceRoomPaymentDetail_备注], 
            T.[源房ID] AS [SourceRoomPaymentDetail_源房ID], 
            T.[缴费项] AS [SourceRoomPaymentDetail_缴费项], 
            T.ID AS SourceRoomPaymentDetail_ID, 
            True AS _from0
        FROM Landlord2Entities.SourceRoomPaymentDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.SourceRoomUpRentalAgreement 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.SourceRoomUpRentalAgreement", @"
    SELECT VALUE -- Constructing SourceRoomUpRentalAgreement
        [Landlord2Model.Store.SourceRoomUpRentalAgreement](T1.[SourceRoomUpRentalAgreement_期始], T1.[SourceRoomUpRentalAgreement_期止], T1.[SourceRoomUpRentalAgreement_月租金], T1.[SourceRoomUpRentalAgreement_源房ID], T1.SourceRoomUpRentalAgreement_ID)
    FROM (
        SELECT 
            T.[期始] AS [SourceRoomUpRentalAgreement_期始], 
            T.[期止] AS [SourceRoomUpRentalAgreement_期止], 
            T.[月租金] AS [SourceRoomUpRentalAgreement_月租金], 
            T.[源房ID] AS [SourceRoomUpRentalAgreement_源房ID], 
            T.ID AS SourceRoomUpRentalAgreement_ID, 
            True AS _from0
        FROM Landlord2Entities.SourceRoomUpRentalAgreement AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.DecorationDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.DecorationDetail", @"
    SELECT VALUE -- Constructing DecorationDetail
        [Landlord2Model.DecorationDetail](T1.[DecorationDetail_日期], T1.[DecorationDetail_项目名称], T1.[DecorationDetail_规格], T1.[DecorationDetail_数量], T1.[DecorationDetail_单位], T1.[DecorationDetail_单价], T1.[DecorationDetail_购买地点], T1.[DecorationDetail_备注], T1.[DecorationDetail_源房ID], T1.[DecorationDetail_装修分类], T1.DecorationDetail_ID)
    FROM (
        SELECT 
            T.[日期] AS [DecorationDetail_日期], 
            T.[项目名称] AS [DecorationDetail_项目名称], 
            T.[规格] AS [DecorationDetail_规格], 
            T.[数量] AS [DecorationDetail_数量], 
            T.[单位] AS [DecorationDetail_单位], 
            T.[单价] AS [DecorationDetail_单价], 
            T.[购买地点] AS [DecorationDetail_购买地点], 
            T.[备注] AS [DecorationDetail_备注], 
            T.[源房ID] AS [DecorationDetail_源房ID], 
            T.[装修分类] AS [DecorationDetail_装修分类], 
            T.ID AS DecorationDetail_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.DecorationDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.GuestRoom 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.GuestRoom", "\r\n    SELECT VALUE -- Constructing GuestRoom\r\n        [Landlord2Model.GuestRoom](" +
                    "T1.[GuestRoom_命名], T1.[GuestRoom_面积], T1.[GuestRoom_含厨房], T1.[GuestRoom_含卫生间], T" +
                    "1.[GuestRoom_租户], T1.[GuestRoom_联系地址], T1.[GuestRoom_身份证号], T1.[GuestRoom_电话1], " +
                    "T1.[GuestRoom_电话2], T1.[GuestRoom_期始], T1.[GuestRoom_期止], T1.[GuestRoom_月租金], T1" +
                    ".[GuestRoom_押金], T1.[GuestRoom_支付月数], T1.[GuestRoom_租赁协议照片1], T1.[GuestRoom_租赁协议" +
                    "照片2], T1.[GuestRoom_租赁协议照片3], T1.[GuestRoom_备注], T1.[GuestRoom_水始码], T1.[GuestRo" +
                    "om_电始码], T1.[GuestRoom_气始码], T1.[GuestRoom_月物业费], T1.[GuestRoom_月宽带费], T1.[Guest" +
                    "Room_月厨房费], T1.[GuestRoom_中介费用], T1.GuestRoom_ID, T1.[GuestRoom_源房ID])\r\n    FROM" +
                    " (\r\n        SELECT \r\n            T.[命名] AS [GuestRoom_命名], \r\n            T.[面积] " +
                    "AS [GuestRoom_面积], \r\n            T.[含厨房] AS [GuestRoom_含厨房], \r\n            T.[含卫" +
                    "生间] AS [GuestRoom_含卫生间], \r\n            T.[租户] AS [GuestRoom_租户], \r\n            T" +
                    ".[联系地址] AS [GuestRoom_联系地址], \r\n            T.[身份证号] AS [GuestRoom_身份证号], \r\n     " +
                    "       T.[电话1] AS [GuestRoom_电话1], \r\n            T.[电话2] AS [GuestRoom_电话2], \r\n " +
                    "           T.[期始] AS [GuestRoom_期始], \r\n            T.[期止] AS [GuestRoom_期止], \r\n " +
                    "           T.[月租金] AS [GuestRoom_月租金], \r\n            T.[押金] AS [GuestRoom_押金], \r" +
                    "\n            T.[支付月数] AS [GuestRoom_支付月数], \r\n            T.[租赁协议照片1] AS [GuestRo" +
                    "om_租赁协议照片1], \r\n            T.[租赁协议照片2] AS [GuestRoom_租赁协议照片2], \r\n            T.[" +
                    "租赁协议照片3] AS [GuestRoom_租赁协议照片3], \r\n            T.[备注] AS [GuestRoom_备注], \r\n     " +
                    "       T.[水始码] AS [GuestRoom_水始码], \r\n            T.[电始码] AS [GuestRoom_电始码], \r\n " +
                    "           T.[气始码] AS [GuestRoom_气始码], \r\n            T.[月物业费] AS [GuestRoom_月物业费" +
                    "], \r\n            T.[月宽带费] AS [GuestRoom_月宽带费], \r\n            T.[月厨房费] AS [GuestR" +
                    "oom_月厨房费], \r\n            T.[中介费用] AS [GuestRoom_中介费用], \r\n            T.ID AS Gue" +
                    "stRoom_ID, \r\n            T.[源房ID] AS [GuestRoom_源房ID], \r\n            True AS _fr" +
                    "om0\r\n        FROM Landlord2ModelStoreContainer.GuestRoom AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.GuestRoomRentalDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.GuestRoomRentalDetail", @"
    SELECT VALUE -- Constructing GuestRoomRentalDetail
        [Landlord2Model.GuestRoomRentalDetail](T1.[GuestRoomRentalDetail_起付日期], T1.[GuestRoomRentalDetail_止付日期], T1.[GuestRoomRentalDetail_付款日期], T1.[GuestRoomRentalDetail_水止码], T1.[GuestRoomRentalDetail_电止码], T1.[GuestRoomRentalDetail_气止码], T1.[GuestRoomRentalDetail_应付金额], T1.[GuestRoomRentalDetail_实付金额], T1.[GuestRoomRentalDetail_付款人], T1.[GuestRoomRentalDetail_收款人], T1.[GuestRoomRentalDetail_备注], T1.[GuestRoomRentalDetail_客房ID], T1.GuestRoomRentalDetail_ID)
    FROM (
        SELECT 
            T.[起付日期] AS [GuestRoomRentalDetail_起付日期], 
            T.[止付日期] AS [GuestRoomRentalDetail_止付日期], 
            T.[付款日期] AS [GuestRoomRentalDetail_付款日期], 
            T.[水止码] AS [GuestRoomRentalDetail_水止码], 
            T.[电止码] AS [GuestRoomRentalDetail_电止码], 
            T.[气止码] AS [GuestRoomRentalDetail_气止码], 
            T.[应付金额] AS [GuestRoomRentalDetail_应付金额], 
            T.[实付金额] AS [GuestRoomRentalDetail_实付金额], 
            T.[付款人] AS [GuestRoomRentalDetail_付款人], 
            T.[收款人] AS [GuestRoomRentalDetail_收款人], 
            T.[备注] AS [GuestRoomRentalDetail_备注], 
            T.[客房ID] AS [GuestRoomRentalDetail_客房ID], 
            T.ID AS GuestRoomRentalDetail_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.GuestRoomRentalDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.GuestRoomRentHistory 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2377);
            viewString.Append("\r\n    SELECT VALUE -- Constructing GuestRoomRentHistory\r\n        [Landlord2Model");
            viewString.Append(".GuestRoomRentHistory](T1.[GuestRoomRentHistory_租户], T1.[GuestRoomRentHistory_联系");
            viewString.Append("地址], T1.[GuestRoomRentHistory_身份证号], T1.[GuestRoomRentHistory_电话1], T1.[GuestRoo");
            viewString.Append("mRentHistory_电话2], T1.[GuestRoomRentHistory_期始], T1.[GuestRoomRentHistory_期止], T");
            viewString.Append("1.[GuestRoomRentHistory_月租金], T1.[GuestRoomRentHistory_押金], T1.[GuestRoomRentHis");
            viewString.Append("tory_支付月数], T1.[GuestRoomRentHistory_备注], T1.[GuestRoomRentHistory_客房ID], T1.Gue");
            viewString.Append("stRoomRentHistory_ID, T1.[GuestRoomRentHistory_租赁协议照片1], T1.[GuestRoomRentHistor");
            viewString.Append("y_租赁协议照片2], T1.[GuestRoomRentHistory_租赁协议照片3], T1.[GuestRoomRentHistory_水始码], T1");
            viewString.Append(".[GuestRoomRentHistory_电始码], T1.[GuestRoomRentHistory_气始码], T1.[GuestRoomRentHis");
            viewString.Append("tory_月物业费], T1.[GuestRoomRentHistory_月宽带费], T1.[GuestRoomRentHistory_月厨房费], T1.[");
            viewString.Append("GuestRoomRentHistory_中介费用], T1.[GuestRoomRentHistory_状态], T1.[GuestRoomRentHisto");
            viewString.Append("ry_操作日期])\r\n    FROM (\r\n        SELECT \r\n            T.[租户] AS [GuestRoomRentHist");
            viewString.Append("ory_租户], \r\n            T.[联系地址] AS [GuestRoomRentHistory_联系地址], \r\n            T.");
            viewString.Append("[身份证号] AS [GuestRoomRentHistory_身份证号], \r\n            T.[电话1] AS [GuestRoomRentHi");
            viewString.Append("story_电话1], \r\n            T.[电话2] AS [GuestRoomRentHistory_电话2], \r\n            T");
            viewString.Append(".[期始] AS [GuestRoomRentHistory_期始], \r\n            T.[期止] AS [GuestRoomRentHistor");
            viewString.Append("y_期止], \r\n            T.[月租金] AS [GuestRoomRentHistory_月租金], \r\n            T.[押金]");
            viewString.Append(" AS [GuestRoomRentHistory_押金], \r\n            T.[支付月数] AS [GuestRoomRentHistory_支");
            viewString.Append("付月数], \r\n            T.[备注] AS [GuestRoomRentHistory_备注], \r\n            T.[客房ID] ");
            viewString.Append("AS [GuestRoomRentHistory_客房ID], \r\n            T.ID AS GuestRoomRentHistory_ID, \r");
            viewString.Append("\n            T.[租赁协议照片1] AS [GuestRoomRentHistory_租赁协议照片1], \r\n            T.[租赁协");
            viewString.Append("议照片2] AS [GuestRoomRentHistory_租赁协议照片2], \r\n            T.[租赁协议照片3] AS [GuestRoom");
            viewString.Append("RentHistory_租赁协议照片3], \r\n            T.[水始码] AS [GuestRoomRentHistory_水始码], \r\n   ");
            viewString.Append("         T.[电始码] AS [GuestRoomRentHistory_电始码], \r\n            T.[气始码] AS [GuestR");
            viewString.Append("oomRentHistory_气始码], \r\n            T.[月物业费] AS [GuestRoomRentHistory_月物业费], \r\n  ");
            viewString.Append("          T.[月宽带费] AS [GuestRoomRentHistory_月宽带费], \r\n            T.[月厨房费] AS [Gu");
            viewString.Append("estRoomRentHistory_月厨房费], \r\n            T.[中介费用] AS [GuestRoomRentHistory_中介费用],");
            viewString.Append(" \r\n            T.[状态] AS [GuestRoomRentHistory_状态], \r\n            T.[操作日期] AS [G");
            viewString.Append("uestRoomRentHistory_操作日期], \r\n            True AS _from0\r\n        FROM Landlord2M");
            viewString.Append("odelStoreContainer.GuestRoomRentHistory AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.GuestRoomRentHistory", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.SourceRoom 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2563);
            viewString.Append("\r\n    SELECT VALUE -- Constructing SourceRoom\r\n        [Landlord2Model.SourceRoo");
            viewString.Append("m](T1.[SourceRoom_房名], T1.[SourceRoom_用途], T1.[SourceRoom_结构], T1.[SourceRoom_建筑");
            viewString.Append("面积], T1.[SourceRoom_室], T1.[SourceRoom_厅], T1.[SourceRoom_卫], T1.[SourceRoom_装修]");
            viewString.Append(", T1.[SourceRoom_权证号], T1.[SourceRoom_房东], T1.[SourceRoom_联系地址], T1.[SourceRoom_");
            viewString.Append("身份证号], T1.[SourceRoom_电话1], T1.[SourceRoom_电话2], T1.[SourceRoom_押金], T1.[SourceR");
            viewString.Append("oom_支付月数], T1.[SourceRoom_租赁协议照片1], T1.[SourceRoom_租赁协议照片2], T1.[SourceRoom_租赁协议");
            viewString.Append("照片3], T1.[SourceRoom_备注], T1.[SourceRoom_月物业费], T1.[SourceRoom_水始码], T1.[SourceR");
            viewString.Append("oom_电始码], T1.[SourceRoom_气始码], T1.[SourceRoom_中介费用], T1.[SourceRoom_月卫生费], T1.[S");
            viewString.Append("ourceRoom_源房东银行卡], T1.[SourceRoom_水表编号], T1.[SourceRoom_电表编号], T1.[SourceRoom_气表");
            viewString.Append("编号], T1.[SourceRoom_水务代扣卫生费], T1.[SourceRoom_月宽带费], T1.[SourceRoom_阶梯水价], T1.[So");
            viewString.Append("urceRoom_阶梯电价], T1.[SourceRoom_气单价], T1.SourceRoom_ID)\r\n    FROM (\r\n        SELE");
            viewString.Append("CT \r\n            T.[房名] AS [SourceRoom_房名], \r\n            T.[用途] AS [SourceRoom_");
            viewString.Append("用途], \r\n            T.[结构] AS [SourceRoom_结构], \r\n            T.[建筑面积] AS [SourceR");
            viewString.Append("oom_建筑面积], \r\n            T.[室] AS [SourceRoom_室], \r\n            T.[厅] AS [Source");
            viewString.Append("Room_厅], \r\n            T.[卫] AS [SourceRoom_卫], \r\n            T.[装修] AS [SourceR");
            viewString.Append("oom_装修], \r\n            T.[权证号] AS [SourceRoom_权证号], \r\n            T.[房东] AS [Sou");
            viewString.Append("rceRoom_房东], \r\n            T.[联系地址] AS [SourceRoom_联系地址], \r\n            T.[身份证号]");
            viewString.Append(" AS [SourceRoom_身份证号], \r\n            T.[电话1] AS [SourceRoom_电话1], \r\n            ");
            viewString.Append("T.[电话2] AS [SourceRoom_电话2], \r\n            T.[押金] AS [SourceRoom_押金], \r\n        ");
            viewString.Append("    T.[支付月数] AS [SourceRoom_支付月数], \r\n            T.[租赁协议照片1] AS [SourceRoom_租赁协议");
            viewString.Append("照片1], \r\n            T.[租赁协议照片2] AS [SourceRoom_租赁协议照片2], \r\n            T.[租赁协议照片");
            viewString.Append("3] AS [SourceRoom_租赁协议照片3], \r\n            T.[备注] AS [SourceRoom_备注], \r\n         ");
            viewString.Append("   T.[月物业费] AS [SourceRoom_月物业费], \r\n            T.[水始码] AS [SourceRoom_水始码], \r\n ");
            viewString.Append("           T.[电始码] AS [SourceRoom_电始码], \r\n            T.[气始码] AS [SourceRoom_气始码");
            viewString.Append("], \r\n            T.[中介费用] AS [SourceRoom_中介费用], \r\n            T.[月卫生费] AS [Sourc");
            viewString.Append("eRoom_月卫生费], \r\n            T.[源房东银行卡] AS [SourceRoom_源房东银行卡], \r\n            T.[水");
            viewString.Append("表编号] AS [SourceRoom_水表编号], \r\n            T.[电表编号] AS [SourceRoom_电表编号], \r\n      ");
            viewString.Append("      T.[气表编号] AS [SourceRoom_气表编号], \r\n            T.[水务代扣卫生费] AS [SourceRoom_水务");
            viewString.Append("代扣卫生费], \r\n            T.[月宽带费] AS [SourceRoom_月宽带费], \r\n            T.[阶梯水价] AS [");
            viewString.Append("SourceRoom_阶梯水价], \r\n            T.[阶梯电价] AS [SourceRoom_阶梯电价], \r\n            T.[");
            viewString.Append("气单价] AS [SourceRoom_气单价], \r\n            T.ID AS SourceRoom_ID, \r\n            Tru");
            viewString.Append("e AS _from0\r\n        FROM Landlord2ModelStoreContainer.SourceRoom AS T\r\n    ) AS");
            viewString.Append(" T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.SourceRoom", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.SourceRoomCheck 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.SourceRoomCheck", @"
    SELECT VALUE -- Constructing SourceRoomCheck
        [Landlord2Model.SourceRoomCheck](T1.[SourceRoomCheck.抄表日期_水_], T1.[SourceRoomCheck_水止码], T1.[SourceRoomCheck_水账户余额], T1.[SourceRoomCheck.抄表日期_电_], T1.[SourceRoomCheck_电止码], T1.[SourceRoomCheck_电账户余额], T1.[SourceRoomCheck.抄表日期_气_], T1.[SourceRoomCheck_气表剩余字数], T1.[SourceRoomCheck_核查人], T1.[SourceRoomCheck_核查时间], T1.[SourceRoomCheck_备注], T1.[SourceRoomCheck_源房ID], T1.SourceRoomCheck_ID)
    FROM (
        SELECT 
            T.[抄表日期(水)] AS [SourceRoomCheck.抄表日期_水_], 
            T.[水止码] AS [SourceRoomCheck_水止码], 
            T.[水账户余额] AS [SourceRoomCheck_水账户余额], 
            T.[抄表日期(电)] AS [SourceRoomCheck.抄表日期_电_], 
            T.[电止码] AS [SourceRoomCheck_电止码], 
            T.[电账户余额] AS [SourceRoomCheck_电账户余额], 
            T.[抄表日期(气)] AS [SourceRoomCheck.抄表日期_气_], 
            T.[气表剩余字数] AS [SourceRoomCheck_气表剩余字数], 
            T.[核查人] AS [SourceRoomCheck_核查人], 
            T.[核查时间] AS [SourceRoomCheck_核查时间], 
            T.[备注] AS [SourceRoomCheck_备注], 
            T.[源房ID] AS [SourceRoomCheck_源房ID], 
            T.ID AS SourceRoomCheck_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.SourceRoomCheck AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.SourceRoomPaymentDetail 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.SourceRoomPaymentDetail", @"
    SELECT VALUE -- Constructing SourceRoomPaymentDetail
        [Landlord2Model.SourceRoomPaymentDetail](T1.[SourceRoomPaymentDetail_缴费时间], T1.[SourceRoomPaymentDetail_缴费金额], T1.[SourceRoomPaymentDetail_期始], T1.[SourceRoomPaymentDetail_期止], T1.[SourceRoomPaymentDetail_付款人], T1.[SourceRoomPaymentDetail_收款人], T1.[SourceRoomPaymentDetail_备注], T1.[SourceRoomPaymentDetail_源房ID], T1.[SourceRoomPaymentDetail_缴费项], T1.SourceRoomPaymentDetail_ID)
    FROM (
        SELECT 
            T.[缴费时间] AS [SourceRoomPaymentDetail_缴费时间], 
            T.[缴费金额] AS [SourceRoomPaymentDetail_缴费金额], 
            T.[期始] AS [SourceRoomPaymentDetail_期始], 
            T.[期止] AS [SourceRoomPaymentDetail_期止], 
            T.[付款人] AS [SourceRoomPaymentDetail_付款人], 
            T.[收款人] AS [SourceRoomPaymentDetail_收款人], 
            T.[备注] AS [SourceRoomPaymentDetail_备注], 
            T.[源房ID] AS [SourceRoomPaymentDetail_源房ID], 
            T.[缴费项] AS [SourceRoomPaymentDetail_缴费项], 
            T.ID AS SourceRoomPaymentDetail_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.SourceRoomPaymentDetail AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.SourceRoomUpRentalAgreement 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.SourceRoomUpRentalAgreement", @"
    SELECT VALUE -- Constructing SourceRoomUpRentalAgreement
        [Landlord2Model.SourceRoomUpRentalAgreement](T1.[SourceRoomUpRentalAgreement_期始], T1.[SourceRoomUpRentalAgreement_期止], T1.[SourceRoomUpRentalAgreement_月租金], T1.[SourceRoomUpRentalAgreement_源房ID], T1.SourceRoomUpRentalAgreement_ID)
    FROM (
        SELECT 
            T.[期始] AS [SourceRoomUpRentalAgreement_期始], 
            T.[期止] AS [SourceRoomUpRentalAgreement_期止], 
            T.[月租金] AS [SourceRoomUpRentalAgreement_月租金], 
            T.[源房ID] AS [SourceRoomUpRentalAgreement_源房ID], 
            T.ID AS SourceRoomUpRentalAgreement_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.SourceRoomUpRentalAgreement AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.DecorationType 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.DecorationType", @"
    SELECT VALUE -- Constructing DecorationType
        [Landlord2Model.Store.DecorationType](T1.[DecorationType_类别])
    FROM (
        SELECT 
            T.[类别] AS [DecorationType_类别], 
            True AS _from0
        FROM Landlord2Entities.DecorationType AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.DecorationType 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.DecorationType", @"
    SELECT VALUE -- Constructing DecorationType
        [Landlord2Model.DecorationType](T1.[DecorationType_类别])
    FROM (
        SELECT 
            T.[类别] AS [DecorationType_类别], 
            True AS _from0
        FROM Landlord2ModelStoreContainer.DecorationType AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2ModelStoreContainer.Remind 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2ModelStoreContainer.Remind", @"
    SELECT VALUE -- Constructing Remind
        [Landlord2Model.Store.Remind](T1.[Remind_提醒时间], T1.[Remind_事项], T1.[Remind_已完成], T1.[Remind_创建日期], T1.[Remind_完成日期], T1.[Remind_客房ID], T1.[Remind_源房ID], T1.Remind_ID)
    FROM (
        SELECT 
            T.[提醒时间] AS [Remind_提醒时间], 
            T.[事项] AS [Remind_事项], 
            T.[已完成] AS [Remind_已完成], 
            T.[创建日期] AS [Remind_创建日期], 
            T.[完成日期] AS [Remind_完成日期], 
            T.[客房ID] AS [Remind_客房ID], 
            T.[源房ID] AS [Remind_源房ID], 
            T.ID AS Remind_ID, 
            True AS _from0
        FROM Landlord2Entities.Remind AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// 返回 Landlord2Entities.Remind 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Landlord2Entities.Remind", @"
    SELECT VALUE -- Constructing Remind
        [Landlord2Model.Remind](T1.[Remind_提醒时间], T1.[Remind_事项], T1.[Remind_已完成], T1.[Remind_创建日期], T1.[Remind_完成日期], T1.[Remind_客房ID], T1.[Remind_源房ID], T1.Remind_ID)
    FROM (
        SELECT 
            T.[提醒时间] AS [Remind_提醒时间], 
            T.[事项] AS [Remind_事项], 
            T.[已完成] AS [Remind_已完成], 
            T.[创建日期] AS [Remind_创建日期], 
            T.[完成日期] AS [Remind_完成日期], 
            T.[客房ID] AS [Remind_客房ID], 
            T.[源房ID] AS [Remind_源房ID], 
            T.ID AS Remind_ID, 
            True AS _from0
        FROM Landlord2ModelStoreContainer.Remind AS T
    ) AS T1");
        }
    }
}


