//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客房租金明细
    {
        public System.DateTime 起付日期 { get; set; }
        public System.DateTime 止付日期 { get; set; }
        public System.DateTime 付款日期 { get; set; }
        public double 水止码 { get; set; }
        public double 电止码 { get; set; }
        public double 气止码 { get; set; }
        public decimal 应付金额 { get; set; }
        public decimal 实付金额 { get; set; }
        public string 付款人 { get; set; }
        public string 收款人 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 客房ID { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual 客房 客房 { get; set; }
    }
}
