//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客房
    {
        public 客房()
        {
            this.客房出租历史记录 = new HashSet<客房出租历史记录>();
            this.客房租金明细 = new HashSet<客房租金明细>();
        }
    
        public string 命名 { get; set; }
        public double 面积 { get; set; }
        public bool 含厨房 { get; set; }
        public bool 含卫生间 { get; set; }
        public string 租户 { get; set; }
        public string 联系地址 { get; set; }
        public string 身份证号 { get; set; }
        public string 电话1 { get; set; }
        public string 电话2 { get; set; }
        public Nullable<System.DateTime> 期始 { get; set; }
        public Nullable<System.DateTime> 期止 { get; set; }
        public decimal 月租金 { get; set; }
        public decimal 押金 { get; set; }
        public short 支付月数 { get; set; }
        public byte[] 租赁协议照片1 { get; set; }
        public byte[] 租赁协议照片2 { get; set; }
        public byte[] 租赁协议照片3 { get; set; }
        public string 备注 { get; set; }
        public double 水始码 { get; set; }
        public double 电始码 { get; set; }
        public double 气始码 { get; set; }
        public decimal 月物业费 { get; set; }
        public decimal 月宽带费 { get; set; }
        public decimal 月厨房费 { get; set; }
        public decimal 中介费用 { get; set; }
        public System.Guid ID { get; set; }
        public System.Guid 源房ID { get; set; }
    
        public virtual ICollection<客房出租历史记录> 客房出租历史记录 { get; set; }
        public virtual ICollection<客房租金明细> 客房租金明细 { get; set; }
        public virtual 源房 源房 { get; set; }
    }
}
