//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class 提醒
    {
        public System.DateTime 提醒时间 { get; set; }
        public string 事项 { get; set; }
        public bool 已完成 { get; set; }
        public System.DateTime 创建日期 { get; set; }
        public Nullable<System.DateTime> 完成日期 { get; set; }
        public Nullable<System.Guid> 客房ID { get; set; }
        public Nullable<System.Guid> 源房ID { get; set; }
        public System.Guid ID { get; set; }
    }
}
