//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class 装修明细
    {
        public System.DateTime 日期 { get; set; }
        public string 项目名称 { get; set; }
        public string 规格 { get; set; }
        public short 数量 { get; set; }
        public string 单位 { get; set; }
        public decimal 单价 { get; set; }
        public string 购买地点 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 源房ID { get; set; }
        public string 装修分类 { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual 源房 源房 { get; set; }
    }
}
