//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLosses
    {
        public Nullable<System.Guid> 源房ID { get; set; }
        public Nullable<System.Guid> 客房ID { get; set; }
        public string 项目 { get; set; }
        public Nullable<decimal> 支出金额 { get; set; }
        public Nullable<System.DateTime> 支出日期 { get; set; }
        public string 备注 { get; set; }
        public System.Guid ID { get; set; }
    }
}
