//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landlord2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceRoomCheck
    {
        public Nullable<System.DateTime> 抄表日期_水_ { get; set; }
        public Nullable<double> 水止码 { get; set; }
        public Nullable<decimal> 水账户余额 { get; set; }
        public Nullable<System.DateTime> 抄表日期_电_ { get; set; }
        public Nullable<double> 电止码 { get; set; }
        public Nullable<decimal> 电账户余额 { get; set; }
        public Nullable<System.DateTime> 抄表日期_气_ { get; set; }
        public Nullable<double> 气表剩余字数 { get; set; }
        public string 核查人 { get; set; }
        public Nullable<System.DateTime> 核查时间 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 源房ID { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual SourceRoom SourceRoom { get; set; }
    }
}
